server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: 1324fara
    url: jdbc:postgresql://localhost:5432/search_engine?rewriteBatchedStatements=true
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
      maxLifeTime: 300000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        generate_statistics: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
# example values

indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox
    - url: https://playback.ru/
      name: PlayBack.Ru
    - url: https://volochek.life/
      name: Волочек
    - url: https://ipfran.ru/
      name: ИПФран.ру
    - url: https://dimonvideo.ru/
      name: Димонвидео.ру
    - url: https://tretyakovgallery.ru/
      name: Третьяков
    - url: https://lutherancathedral.ru/
      name: Lutheran Cathedral
    - url: https://dombulgakova.ru/
      name: Булгаков
    - url: https://svetlovka.ru/
      name: Светловка.ру

crawler-settings:
  user-agent: Chrome/59.1.3030.111 Safari/538.4
  referrer: https://www.ya.ru/

logging:
  level:
    org.springframework.web: error
    org.hibernate: error
  file.name: logs/app.log